# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/docker/

sudo: required
dist: trusty

services:
  - docker

install:
  # - hg clone http://www.octave.org/hg/octave
  - |
    curl -L -o octave.tar.xz http://ftp.gnu.org/gnu/octave/octave-4.2.1.tar.xz
    mkdir octave
    tar xf octave.tar.xz -C octave --strip-components 1

script:
  - docker --version
  - docker pull ubuntu:17.04
  - mkdir build
  - docker run -t -v $PWD/sh:/sh -v $PWD/octave:/octave -v $PWD/build:/build -w /sh ubuntu:17.04 ./build.sh