# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/docker/

sudo: required
dist: trusty

services:
  - docker

install:
  - hg clone http://www.octave.org/hg/octave

script:
  - docker --version
  - docker pull ubuntu:17.04
  - docker run -t -v $PWD/sh:/sh" -v $PWD/octave:/octave -w /sh ubuntu:17.04 ./build.sh